import { Card } from '@/components/ui/card'

import ProductDatatable, { type Item } from '@/components/shadcn-studio/blocks/datatable-product-graph'

const productData: Item[] = [
  {
    id: '1',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-3.png',
    product: 'Samsung galaxy s35',
    brand: 'Samsung',
    graphData: [
      { month: 'January', sales: 0 },
      { month: 'February', sales: 12 },
      { month: 'March', sales: 5 },
      { month: 'April', sales: 12 },
      { month: 'May', sales: 8 },
      { month: 'June', sales: 2 },
      { month: 'July', sales: 8 },
      { month: 'August', sales: 12 },
      { month: 'September', sales: 3 },
      { month: 'October', sales: 10 },
      { month: 'November', sales: 2 },
      { month: 'December', sales: 17 }
    ],
    price: 32,
    orders: 132,
    orderTrend: 'up',
    sales: 23
  },
  {
    id: '2',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-4.png',
    product: 'Apple MacBook Pro',
    brand: 'Apple',
    graphData: [
      { month: 'January', sales: 2 },
      { month: 'February', sales: 12 },
      { month: 'March', sales: 5 },
      { month: 'April', sales: 12 },
      { month: 'May', sales: 17 },
      { month: 'June', sales: 8 },
      { month: 'July', sales: 8 },
      { month: 'August', sales: 15 },
      { month: 'September', sales: 1 },
      { month: 'October', sales: 6 },
      { month: 'November', sales: 16 },
      { month: 'December', sales: 10 }
    ],
    price: 280,
    orders: 116,
    orderTrend: 'up',
    sales: 10
  },
  {
    id: '3',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-5.png',
    product: 'Sony WH-1000XM4',
    brand: 'Sony',
    graphData: [
      { month: 'January', sales: 20 },
      { month: 'February', sales: 3 },
      { month: 'March', sales: 18 },
      { month: 'April', sales: 4 },
      { month: 'May', sales: 12 },
      { month: 'June', sales: 3 },
      { month: 'July', sales: 11 },
      { month: 'August', sales: 4 },
      { month: 'September', sales: 12 },
      { month: 'October', sales: 3 },
      { month: 'November', sales: 6 },
      { month: 'December', sales: 4 }
    ],
    price: 120,
    orders: 250,
    orderTrend: 'down',
    sales: -8
  },
  {
    id: '4',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-6.png',
    product: 'Dell XPS 13',
    brand: 'Dell',
    graphData: [
      { month: 'January', sales: 20 },
      { month: 'February', sales: 15 },
      { month: 'March', sales: 18 },
      { month: 'April', sales: 14 },
      { month: 'May', sales: 10 },
      { month: 'June', sales: 13 },
      { month: 'July', sales: 6 },
      { month: 'August', sales: 10 },
      { month: 'September', sales: 7 },
      { month: 'October', sales: 3 },
      { month: 'November', sales: 5 },
      { month: 'December', sales: 13 }
    ],
    price: 250,
    orders: 23,
    orderTrend: 'up',
    sales: 12
  },
  {
    id: '5',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-7.png',
    product: 'Smart band 4',
    brand: 'Xiaomi',
    graphData: [
      { month: 'January', sales: 20 },
      { month: 'February', sales: 15 },
      { month: 'March', sales: 18 },
      { month: 'April', sales: 14 },
      { month: 'May', sales: 10 },
      { month: 'June', sales: 13 },
      { month: 'July', sales: 8 },
      { month: 'August', sales: 5 },
      { month: 'September', sales: 9 },
      { month: 'October', sales: 4 },
      { month: 'November', sales: 8 },
      { month: 'December', sales: 3 }
    ],
    price: 12,
    orders: 592,
    orderTrend: 'down',
    sales: 6
  },
  {
    id: '6',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-8.png',
    product: 'Sony PlayStation 5',
    brand: 'Sony',
    graphData: [
      { month: 'January', sales: 7 },
      { month: 'February', sales: 2 },
      { month: 'March', sales: 10 },
      { month: 'April', sales: 7 },
      { month: 'May', sales: 3 },
      { month: 'June', sales: 12 },
      { month: 'July', sales: 16 },
      { month: 'August', sales: 10 },
      { month: 'September', sales: 17 },
      { month: 'October', sales: 11 },
      { month: 'November', sales: 18 },
      { month: 'December', sales: 22 }
    ],
    price: 160,
    orders: 23,
    orderTrend: 'up',
    sales: 12
  },
  {
    id: '7',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-9.png',
    product: 'OnePlus 15 Pro',
    brand: 'OnePlus',
    graphData: [
      { month: 'January', sales: 5 },
      { month: 'February', sales: 12 },
      { month: 'March', sales: 8 },
      { month: 'April', sales: 16 },
      { month: 'May', sales: 22 },
      { month: 'June', sales: 15 },
      { month: 'July', sales: 18 },
      { month: 'August', sales: 11 },
      { month: 'September', sales: 5 },
      { month: 'October', sales: 15 },
      { month: 'November', sales: 20 },
      { month: 'December', sales: 12 }
    ],
    price: 899,
    orders: 87,
    orderTrend: 'up',
    sales: 15
  },
  {
    id: '8',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-10.png',
    product: 'Apple magic mouse',
    brand: 'Apple',
    graphData: [
      { month: 'January', sales: 15 },
      { month: 'February', sales: 18 },
      { month: 'March', sales: 14 },
      { month: 'April', sales: 20 },
      { month: 'May', sales: 16 },
      { month: 'June', sales: 12 },
      { month: 'July', sales: 10 },
      { month: 'August', sales: 8 },
      { month: 'September', sales: 11 },
      { month: 'October', sales: 9 },
      { month: 'November', sales: 7 },
      { month: 'December', sales: 5 }
    ],
    price: 79,
    orders: 156,
    orderTrend: 'down',
    sales: -12
  },
  {
    id: '9',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-11.png',
    product: 'Wooden Chair',
    brand: 'Ikea',
    graphData: [
      { month: 'January', sales: 8 },
      { month: 'February', sales: 12 },
      { month: 'March', sales: 18 },
      { month: 'April', sales: 10 },
      { month: 'May', sales: 18 },
      { month: 'June', sales: 15 },
      { month: 'July', sales: 22 },
      { month: 'August', sales: 15 },
      { month: 'September', sales: 10 },
      { month: 'October', sales: 2 },
      { month: 'November', sales: 8 },
      { month: 'December', sales: 14 }
    ],
    price: 149,
    orders: 234,
    orderTrend: 'up',
    sales: 28
  },
  {
    id: '10',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-12.png',
    product: 'Nike Jordan 1',
    brand: 'Nike',
    graphData: [
      { month: 'January', sales: 2 },
      { month: 'February', sales: 4 },
      { month: 'March', sales: 2 },
      { month: 'April', sales: 6 },
      { month: 'May', sales: 4 },
      { month: 'June', sales: 8 },
      { month: 'July', sales: 6 },
      { month: 'August', sales: 10 },
      { month: 'September', sales: 8 },
      { month: 'October', sales: 12 },
      { month: 'November', sales: 10 },
      { month: 'December', sales: 14 }
    ],
    price: 180,
    orders: 189,
    orderTrend: 'up',
    sales: 35
  },
  {
    id: '11',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-13.png',
    product: 'Nintendo Switch Pro',
    brand: 'Nintendo',
    graphData: [
      { month: 'January', sales: 7 },
      { month: 'February', sales: 15 },
      { month: 'March', sales: 21 },
      { month: 'April', sales: 14 },
      { month: 'May', sales: 21 },
      { month: 'June', sales: 13 },
      { month: 'July', sales: 8 },
      { month: 'August', sales: 16 },
      { month: 'September', sales: 8 },
      { month: 'October', sales: 15 },
      { month: 'November', sales: 7 },
      { month: 'December', sales: 13 }
    ],
    price: 349,
    orders: 67,
    orderTrend: 'down',
    sales: -8
  },
  {
    id: '12',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-14.png',
    product: 'Apple Watch 2',
    brand: 'Apple',
    graphData: [
      { month: 'January', sales: 22 },
      { month: 'February', sales: 16 },
      { month: 'March', sales: 10 },
      { month: 'April', sales: 15 },
      { month: 'May', sales: 8 },
      { month: 'June', sales: 2 },
      { month: 'July', sales: 9 },
      { month: 'August', sales: 14 },
      { month: 'September', sales: 20 },
      { month: 'October', sales: 17 },
      { month: 'November', sales: 12 },
      { month: 'December', sales: 16 }
    ],
    price: 299,
    orders: 145,
    orderTrend: 'up',
    sales: 22
  },
  {
    id: '13',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-15.png',
    product: 'Samsung Note 10 Pro',
    brand: 'Samsung',
    graphData: [
      { month: 'January', sales: 14 },
      { month: 'February', sales: 16 },
      { month: 'March', sales: 10 },
      { month: 'April', sales: 18 },
      { month: 'May', sales: 13 },
      { month: 'June', sales: 6 },
      { month: 'July', sales: 11 },
      { month: 'August', sales: 18 },
      { month: 'September', sales: 12 },
      { month: 'October', sales: 15 },
      { month: 'November', sales: 10 },
      { month: 'December', sales: 14 }
    ],
    price: 599,
    orders: 28,
    orderTrend: 'down',
    sales: -25
  },
  {
    id: '14',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-16.png',
    product: 'Ray Ban Aviator',
    brand: 'Ray Ban',
    graphData: [
      { month: 'January', sales: 20 },
      { month: 'February', sales: 18 },
      { month: 'March', sales: 12 },
      { month: 'April', sales: 16 },
      { month: 'May', sales: 10 },
      { month: 'June', sales: 16 },
      { month: 'July', sales: 12 },
      { month: 'August', sales: 8 },
      { month: 'September', sales: 15 },
      { month: 'October', sales: 10 },
      { month: 'November', sales: 16 },
      { month: 'December', sales: 11 }
    ],
    price: 165,
    orders: 198,
    orderTrend: 'up',
    sales: 18
  },
  {
    id: '15',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-4.png',
    product: 'Macbook Air M2',
    brand: 'Apple',
    graphData: [
      { month: 'January', sales: 8 },
      { month: 'February', sales: 12 },
      { month: 'March', sales: 16 },
      { month: 'April', sales: 10 },
      { month: 'May', sales: 4 },
      { month: 'June', sales: 11 },
      { month: 'July', sales: 15 },
      { month: 'August', sales: 10 },
      { month: 'September', sales: 14 },
      { month: 'October', sales: 18 },
      { month: 'November', sales: 14 },
      { month: 'December', sales: 20 }
    ],
    price: 1199,
    orders: 73,
    orderTrend: 'up',
    sales: 14
  },
  {
    id: '16',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-6.png',
    product: 'Samsung Book 6',
    brand: 'Samsung',
    graphData: [
      { month: 'January', sales: 6 },
      { month: 'February', sales: 8 },
      { month: 'March', sales: 14 },
      { month: 'April', sales: 9 },
      { month: 'May', sales: 4 },
      { month: 'June', sales: 11 },
      { month: 'July', sales: 16 },
      { month: 'August', sales: 10 },
      { month: 'September', sales: 18 },
      { month: 'October', sales: 14 },
      { month: 'November', sales: 9 },
      { month: 'December', sales: 14 }
    ],
    price: 849,
    orders: 45,
    orderTrend: 'up',
    sales: 8
  },
  {
    id: '17',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-10.png',
    product: 'Apple Magic Mouse 2',
    brand: 'Apple',
    graphData: [
      { month: 'January', sales: 21 },
      { month: 'February', sales: 17 },
      { month: 'March', sales: 12 },
      { month: 'April', sales: 16 },
      { month: 'May', sales: 20 },
      { month: 'June', sales: 13 },
      { month: 'July', sales: 8 },
      { month: 'August', sales: 13 },
      { month: 'September', sales: 9 },
      { month: 'October', sales: 5 },
      { month: 'November', sales: 10 },
      { month: 'December', sales: 15 }
    ],
    price: 99,
    orders: 112,
    orderTrend: 'down',
    sales: -18
  },
  {
    id: '18',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-16.png',
    product: 'Ray Ban EyeCat',
    brand: 'Ray Ban',
    graphData: [
      { month: 'January', sales: 16 },
      { month: 'February', sales: 13 },
      { month: 'March', sales: 18 },
      { month: 'April', sales: 21 },
      { month: 'May', sales: 16 },
      { month: 'June', sales: 11 },
      { month: 'July', sales: 7 },
      { month: 'August', sales: 2 },
      { month: 'September', sales: 8 },
      { month: 'October', sales: 13 },
      { month: 'November', sales: 18 },
      { month: 'December', sales: 15 }
    ],
    price: 195,
    orders: 156,
    orderTrend: 'up',
    sales: 12
  },
  {
    id: '19',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-8.png',
    product: 'Xbox Series X',
    brand: 'Microsoft',
    graphData: [
      { month: 'January', sales: 15 },
      { month: 'February', sales: 8 },
      { month: 'March', sales: 13 },
      { month: 'April', sales: 19 },
      { month: 'May', sales: 12 },
      { month: 'June', sales: 18 },
      { month: 'July', sales: 21 },
      { month: 'August', sales: 17 },
      { month: 'September', sales: 12 },
      { month: 'October', sales: 8 },
      { month: 'November', sales: 13 },
      { month: 'December', sales: 19 }
    ],
    price: 499,
    orders: 91,
    orderTrend: 'up',
    sales: 25
  },
  {
    id: '20',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-4.png',
    product: 'Macbook Pro M4',
    brand: 'Apple',
    graphData: [
      { month: 'January', sales: 3 },
      { month: 'February', sales: 9 },
      { month: 'March', sales: 13 },
      { month: 'April', sales: 18 },
      { month: 'May', sales: 14 },
      { month: 'June', sales: 20 },
      { month: 'July', sales: 12 },
      { month: 'August', sales: 7 },
      { month: 'September', sales: 13 },
      { month: 'October', sales: 5 },
      { month: 'November', sales: 11 },
      { month: 'December', sales: 6 }
    ],
    price: 1999,
    orders: 42,
    orderTrend: 'up',
    sales: 32
  },
  {
    id: '21',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-8.png',
    product: 'Play Station 4',
    brand: 'Sony',
    graphData: [
      { month: 'January', sales: 13 },
      { month: 'February', sales: 19 },
      { month: 'March', sales: 12 },
      { month: 'April', sales: 3 },
      { month: 'May', sales: 12 },
      { month: 'June', sales: 9 },
      { month: 'July', sales: 14 },
      { month: 'August', sales: 20 },
      { month: 'September', sales: 14 },
      { month: 'October', sales: 22 },
      { month: 'November', sales: 18 },
      { month: 'December', sales: 13 }
    ],
    price: 299,
    orders: 34,
    orderTrend: 'down',
    sales: -35
  },
  {
    id: '22',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-15.png',
    product: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    graphData: [
      { month: 'January', sales: 4 },
      { month: 'February', sales: 7 },
      { month: 'March', sales: 11 },
      { month: 'April', sales: 16 },
      { month: 'May', sales: 22 },
      { month: 'June', sales: 18 },
      { month: 'July', sales: 14 },
      { month: 'August', sales: 9 },
      { month: 'September', sales: 2 },
      { month: 'October', sales: 8 },
      { month: 'November', sales: 13 },
      { month: 'December', sales: 19 }
    ],
    price: 1299,
    orders: 68,
    orderTrend: 'up',
    sales: 28
  },
  {
    id: '23',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-11.png',
    product: 'Rocking Chair',
    brand: 'Ikea',
    graphData: [
      { month: 'January', sales: 12 },
      { month: 'February', sales: 15 },
      { month: 'March', sales: 18 },
      { month: 'April', sales: 22 },
      { month: 'May', sales: 19 },
      { month: 'June', sales: 14 },
      { month: 'July', sales: 20 },
      { month: 'August', sales: 16 },
      { month: 'September', sales: 8 },
      { month: 'October', sales: 13 },
      { month: 'November', sales: 6 },
      { month: 'December', sales: 11 }
    ],
    price: 225,
    orders: 187,
    orderTrend: 'up',
    sales: 16
  },
  {
    id: '24',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-12.png',
    product: 'Nike Air Max',
    brand: 'Nike',
    graphData: [
      { month: 'January', sales: 22 },
      { month: 'February', sales: 18 },
      { month: 'March', sales: 12 },
      { month: 'April', sales: 17 },
      { month: 'May', sales: 19 },
      { month: 'June', sales: 14 },
      { month: 'July', sales: 20 },
      { month: 'August', sales: 16 },
      { month: 'September', sales: 8 },
      { month: 'October', sales: 13 },
      { month: 'November', sales: 6 },
      { month: 'December', sales: 11 }
    ],
    price: 140,
    orders: 298,
    orderTrend: 'up',
    sales: 26
  },
  {
    id: '25',
    productImage: 'https://cdn.shadcnstudio.com/ss-assets/blocks/data-table/image-7.png',
    product: 'Fitbit Versa 4',
    brand: 'Fitbit',
    graphData: [
      { month: 'January', sales: 18 },
      { month: 'February', sales: 20 },
      { month: 'March', sales: 23 },
      { month: 'April', sales: 16 },
      { month: 'May', sales: 7 },
      { month: 'June', sales: 12 },
      { month: 'July', sales: 18 },
      { month: 'August', sales: 13 },
      { month: 'September', sales: 18 },
      { month: 'October', sales: 11 },
      { month: 'November', sales: 4 },
      { month: 'December', sales: 9 }
    ],
    price: 199,
    orders: 167,
    orderTrend: 'down',
    sales: -15
  }
]

const DataTablePreview = () => {
  return (
    <div className='py-8 sm:py-16 lg:py-24'>
      <div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8'>
        <Card className='mx-auto w-full max-w-250 py-0'>
          <ProductDatatable data={productData} />
        </Card>
      </div>
    </div>
  )
}

export default DataTablePreview
